include: package:lint/analysis_options_package.yaml

linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
    constant_identifier_names: false
    use_setter_to_change_properties: false
    file_names: false
    overridden_fields: false
    prefer_constructors_over_static_methods: false
    use_setters_to_change_properties: false
    sort_pub_dependencies: false
    library_private_types_in_public_api: false
    require_trailing_commas: false
    use_build_context_synchronously: false
    always_use_package_imports: false
    eol_at_end_of_file: false
    prefer_null_aware_method_calls: false